/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:02177485-71ba-4c10-b892-c613ba2619ae",
    "aws_cognito_region": "us-east-2",
    "oauth": {},
    "aws_mobile_analytics_app_id": "812f5b6d7d7a4c40999d1532139daaf0",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
